#
# TSvnPwd project AppVeyor build configuration
#

version: 1.0.0-b{build}

os: Visual Studio 2015

configuration:
  - Release
  - Debug

platform: x86

init:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 8)

build:
  project: TSvnPwd.sln
  verbosity: minimal

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'
  assembly_informational_version: '1.0.0-b{build}-$(GIT_HASH)'

artifacts:
  - path: bin\$(configuration)\TSvnPwd.exe

branches:
  except:
    - gh-pages
